version: "1.1"

services:
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: todo_backend
    command: python main.py
    ports:
      - "8000:8000"
    depends_on:
      - mongo  
    networks:
      - app-network
      
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: todo_frontend
    command: npm run start
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local