version: "3"

services:

  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: todo_backend
    command: python main.py
    ports:
      - "8000:8000"
    depends_on:
      - mongo  
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: todo_frontend
    # command: npm run start
    depends_on:
      - backend
    ports:
      - "80:80"
    
networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local